config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'goals#index'
  resources :static_pages do
    collection do
      get 'about'
      get 'help'
    end
  end

  resources :users do
    resources :goals, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :goals, only: [:new, :index] do
    resources :phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :minds
  end

  resources :phases, only: [:show] do
    resources :tasks
    resources :comments
  end

  resources :tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :phases, only: [:index, :edit, :update], defaults: { format: 'json' }
  end

  resources :teams do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    member do
      get 'activate_user'
      get 'deactivate_user'
    end
  end

  resources :projects, only: [:index] do
    resources :project_phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :project_minds
  end

  resources :project_phases, only: [:show] do
    resources :project_tasks
    resources :project_comments
  end

  resources :project_tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :project_phases, only: :index, defaults: { format: 'json' }
  end
end

app/models/project_mind.rb
class ProjectMind < ApplicationRecord
  validates :title, presence: true
  belongs_to :project
end

app/controllers/project_minds_controller.rb
class ProjectMindsController < ApplicationController
  before_action :move_to_sign_in
  before_action :set_project_mind, only: [:edit, :update, :destroy]

  def new
    @project_mind = ProjectMind.new
    @project = Project.find(params[:project_id])
  end

  def create
    @project_mind = ProjectMind.new(project_mind_params)
    if @project_mind.save
      redirect_to team_project_path(@project_mind.project.team, @project_mind.project)
    else
      @project = Project.find(params[:project_id])
      render :new
    end
  end

  def edit
    @project = @project_mind.project
  end

  def update
    if @project_mind.update(project_mind_params)
      redirect_to team_project_path(@project_mind.project.team, @project_mind.project)
    else
      render :edit
    end
  end

  def destroy
    project = @project_mind.project
    @project_mind.destroy
    redirect_to team_project_path(project.team, project)
  end

  private
    def project_mind_params
      params.require(:project_mind).permit(:title).merge(project_id: params[:project_id])
    end

    def set_project_mind
      @project_mind = ProjectMind.find(params[:id])
    end
end

app/views/project_minds/edit.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'edit')
        タイトルの編集
    = form_with model: [@project, @project_mind], url: project_project_mind_path, class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"

app/views/project_minds/new.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'plus-circle')
        リマインドの新規作成
    = form_with model: [@project, @project_mind], url: project_project_minds_path, class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"