config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'goals#index'
  resources :static_pages do
    collection do
      get 'about'
      get 'help'
    end
  end

  resources :users do
    resources :goals, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :goals, only: [:new, :index] do
    resources :phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :minds
  end

  resources :phases, only: [:show] do
    resources :tasks
    resources :comments
  end

  resources :tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :phases, only: [:index, :edit, :update], defaults: { format: 'json' }
  end

  resources :teams do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    member do
      get 'activate_user'
      get 'deactivate_user'
    end
  end

  resources :projects, only: [:index] do
    resources :project_phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :project_minds
  end

  resources :project_phases, only: [:show] do
    resources :project_tasks
    resources :project_comments
  end

  resources :project_tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :project_phases, only: :index, defaults: { format: 'json' }
  end
end

app/views/shared/_header.html.haml
%header
  .header-items
    .header-items__left
      .header-items__left__links
        - if user_signed_in?
          %button
            = link_to goals_path do
              = icon('fa', 'house-user')
        - else
          = link_to new_user_session_path do
            = icon('fa', 'user-lock')
            Log in
    .header-items__right
      .header-items__right__menu
        .header-items__right__menu__box
          %button#header__btn
            = icon('fa', 'user-friends')
            Team
          #header__panel
            .header-items__right__menu__box__links
              -if user_signed_in?
                = link_to 'チーム作成', new_team_path(current_user)
              .header-items__right__menu__box__links
                = link_to 'チーム一覧', teams_path
              .header-items__right__links__menu
                = link_to 'Projects', projects_path
        .header-items__right__menu__box
          %button#header__btn2
            = icon('fa','user-circle')
            Account
          #header__panel2
            .header-items__right__menu__box__links
              -if user_signed_in?
                = link_to 'ログアウト', destroy_user_session_path, method: :delete
      .header-items__right__menu__goal-new-link
        = link_to new_goal_path do
          = icon('fa', 'plus')
          目標の新規作成