config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'goals#index'
  resources :static_pages do
    collection do
      get 'about'
      get 'help'
    end
  end

  resources :users do
    resources :goals, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :goals, only: [:new, :index] do
    resources :phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :minds
  end

  resources :phases, only: [:show] do
    resources :tasks
    resources :comments
  end

  resources :tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :phases, only: [:index, :edit, :update], defaults: { format: 'json' }
  end

  resources :teams do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    member do
      get 'activate_user'
      get 'deactivate_user'
    end
  end

  resources :projects, only: [:index] do
    resources :project_phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :project_minds
  end

  resources :project_phases, only: [:show] do
    resources :project_tasks
    resources :project_comments
  end

  resources :project_tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :project_phases, only: :index, defaults: { format: 'json' }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  has_many :project_phases, dependent: :destroy
  has_many :project_minds, dependent: :destroy
  belongs_to :team
  # has_many :phases, dependent: :destroy
  # has_many :minds, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :move_to_sign_in
  before_action :check_member, except: [:index, :new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def new
    @project = Project.new
    @team = Team.find(params[:team_id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      @team = Team.find(params[:team_id])
      render :new
    end
  end

  def index
    @teams = current_user.teams
    @projects = Project.all
  end

  def show
    @project_phase = ProjectPhase.find_by(title: @project.phase_title)
    @project_phases = @project.project_phases.where.not(title: @project.phase_title).order("created_at ASC")
    @project_minds = @project.project_minds
    if @project_phase.present?
      @project_tasks = sort_created_at(@project_phase.project_tasks)
      @project_comments = sort_created_at(@project_phase.project_comments)
    end
  end

  def edit
    @team = @project.team
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      @team = @project.team
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :phase_title).merge(team_id: params[:team_id])
    end

    def check_member
      unless Team.find(params[:team_id]).users.exists?(id: current_user.id)
        redirect_to root_path
      end
    end

    def set_project
      @project = Project.find(params[:id])
    end
end

app/views/projects/edit.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'edit')
        プロジェクトの編集
    = form_with model: [@team, @project], url: team_project_path, class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"

app/views/projects/index.html.haml
.goal-wrapper
  = render 'shared/header'
  .goal-index__container
    - if @projects.present?
      .goal-index__container__header
        .goal-index__container__header__title
          %p
            = "プロジェクトの総数：#{@projects.count}" 
        .goal-index__container__header__edit
          -# = link_to new_user_goal_path(current_user) do
          -#   = icon('fa', 'plus-circle')
          -#   目標を追加
      - @projects.each do |project|  
        .goal-index__container__contents
          .goal-index__container__contents__top
            .goal-index__container__contents__top__title
              %p
                = project.title
            .goal-index__container__contents__top__links
              = link_to edit_team_project_path(project.team, project) do
                = icon('fa', 'edit')
              = link_to team_project_path(project.team, project), method: :delete do
                = icon('fa', 'trash')
          .goal-index__container__contents__status
            - if project.project_phases.present?
              - if project.phase_title.present?
                - project.project_phases.each do |phase|
                  - if phase.title == project.phase_title
                    .goal-index__container__contents__status__phase
                      %p
                        %span
                          = icon('fa', 'check-circle')
                        現在のフェーズ
                      %p.goal-index__container__contents__status__phase__title
                        = "・#{project.phase_title}"
                      .goal-index__container__contents__status__phase__task
                        .goal-index__container__contents__status__phase__task__count
                          %p
                            = "完了したタスク数 :#{sort_tasks(phase.project_tasks).count}"
                          %p
                            = "残りのタスク数 :#{phase.project_tasks.count - sort_tasks(phase.project_tasks).count}"
                        .goal-index__container__contents__status__phase__task__show
                          = link_to team_project_path(project.team, project) do
                            %span
                              = icon('fa', 'vote-yea')
                            詳細ページ
                    .goal-index__container__contents__status__task-unfinished
                      .goal-show-info__contents__bottom__accbox
                        %label.goal-show-info__contents__bottom__accbox__label
                          %span
                            = icon('fa', 'tasks')
                          担当タスクを確認
                          = icon('fa', 'angle-down')
                          %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
                          .goal-show-info__contents__bottom__accbox__accshow
                            .goal-index__container__contents__status__task-unfinished__task
                              - if phase.project_tasks.present?
                                - phase.project_tasks.each do |task|
                                  - if task.user_id == current_user.id
                                    - if task.task_flg == true
                                      %p
                                        = icon('fa', 'check-square')
                                        = task.title
                                    - else
                                      %p
                                        = icon('fa', 'caret-right')
                                        = task.title
                                  - else
                              - else
                                %p タスク無し
              - else
                .goal-index__container__contents__status__phase
                  %p.goal-index__container__contents__status__phase__info
                    フェーズが設定されていません
                .goal-index__container__contents__status__phase__task
                  .goal-index__container__contents__status__phase__task__count
                  .goal-index__container__contents__status__phase__task__show
                    = link_to team_project_path(project.team, project) do
                      %span
                        = icon('fa', 'vote-yea')
                      詳細ページ                                 
            - else
              .goal-index__container__contents__status__phase
                %p
                  詳細ページでフェーズを作成して下さい
              .goal-index__container__contents__status__phase__task
                .goal-index__container__contents__status__phase__task__count
                .goal-index__container__contents__status__phase__task__show
                  = link_to team_project_path(project.team, project) do
                    %span
                      = icon('fa', 'vote-yea')
                    詳細ページ
    - else
      .goal-index__container__header
        .goal-index__container__header__title
          %p
            = "プロジェクトの総数：0" 
        .goal-index__container__header__edit
          参加しているプロジェクトはありません

app/views/projects/new.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'plus-circle')
        プロジェクトの新規作成
    = form_with model: [@team, @project], url: team_projects_path, class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"

app/views/projects/show.html.haml
.goal-wrapper
  = render 'shared/header'
  .goal-show-info
    .goal-show-info__header
      %h2.goal-show-info__header__title
        = @project.title
      .goal-show-info__header__remind
        - if @project_minds.present?
          .goal-show-info__header__remind__title
            %p 
              = icon('fa', 'clipboard-list')
              リマインド
          - @project_minds.each do |mind|
            .goal-show-info__header__remind__index
              %p 
                = "・#{mind.title}"
              .goal-show-info__header__remind__index__link
                = link_to edit_project_project_mind_path(@project,mind) do
                  = icon('fa', 'edit')
                = link_to project_project_mind_path(@project,mind), method: :delete do
                  = icon('fa', 'trash')
        - else
          %p リマインドはありません
      .goal-show-info__header__link
        = link_to new_project_project_mind_path(@project) do
          %span.blue
            = icon('fa', 'plus-circle')
          リマインドを追加する
    - if @project_phase.present?
      .goal-show-info__contents
        .goal-show-info__contents__phase-header
          .goal-show-info__contents__phase-header__title
            .goal-show-info__contents__phase-header__title__nav
              %p 
                %span
                  = icon('fa', 'check-circle')
                進行中のフェーズ
              .goal-show-info__contents__phase-header__title__nav__link
                = link_to edit_project_project_phase_path(@project,@project_phase) do
                  = icon('fa', 'edit')
                = link_to project_project_phase_path(@project,@project_phase), method: :delete do
                  = icon('fa', 'trash')
            %p.goal-show-info__contents__phase-header__title__phase
              = @project_phase.title
        .goal-show-info__contents__top
          .goal-show-info__contents__top__phase
            %p#phase_data{data: {phase: {id: @project_phase.id}}}
          .goal-show-info__contents__top__tasks
            .goal-show-info__contents__top__tasks__title
              %p タスクのチェック
            - if @project_tasks.present?
              - @project_tasks.each do |task|
                .goal-show-info__contents__top__tasks__index
                  .goal-show-info__contents__top__tasks__index__timestamp
                    %p.goal-show-info__contents__accbox__accshow__checkbox__timestamp
                      - if task.task_flg == true
                        = "#{task.updated_at.year}年#{task.updated_at.mon}月#{task.updated_at.day}日 担当: #{task.user.name}"
                  .goal-show-info__contents__top__tasks__index__checkbox
                    .goal-show-info__contents__top__tasks__index__checkbox__main
                      %label.goal-show-info__contents__accbox__accshow__checkbox__label
                        - if task.user_id == current_user.id
                          - if task.task_flg == true
                            %input.project-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox", :checked => "checked"}
                          - else
                            %input.project-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox"}
                          = task.title
                          #task{data: {task: {id: task.id}}}
                        - else
                          - if task.task_flg == true
                            %span
                              = icon('fa', 'check-square')
                          - else                            
                          = task.title
                          #task{data: {task: {id: task.id}}}
                    .goal-show-info__contents__top__tasks__index__checkbox__link
                      = link_to edit_project_phase_project_task_path(@project_phase, task) do
                        = icon('fa', 'edit')
                      = link_to new_project_phase_project_task_path(@project_phase), method: :delete do
                        = icon('fa', 'trash')
            - else
              %p タスクはありません          
            .goal-show-info__contents__top__tasks__create
              = link_to new_project_phase_project_task_path(@project_phase) do
                = icon('fa', 'tasks')
                タスクの作成
        .goal-show-info__contents__bottom
          .goal-show-info__contents__bottom__accbox
            %label.goal-show-info__contents__bottom__accbox__label
              %span
                = icon('fa', 'comment')
              コメントメニュー
              = icon('fa', 'angle-down')
              %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
              .goal-show-info__contents__bottom__accbox__accshow
                .goal-show-info__contents__bottom__comments
                  .goal-show-info__contents__bottom__comments__content
                    - if @project_comments.present?
                      - @project_comments.each do |comment|
                        .goal-show-info__contents__bottom__comments__content__comment
                          %p
                            = icon('fa', 'user-edit')
                            = comment.user.name
                            %br
                            = comment.content
                          = link_to project_phase_project_comment_path(@project_phase,comment), method: :delete do
                            = icon('fa', 'trash')
                  .goal-show-info__contents__bottom__comments__form{data: {commentphase: {id: @project_phase.id}}}
                    .token{data: {authenticity: {token: form_authenticity_token}}}
                    %input{:type => "text", :placeholder => "コメント"}
                    %button.project_comment_button
                      = icon('fa', 'paper-plane')
      .goal-show-info__create
        = link_to new_project_project_phase_path(@project) do
          %span.blue
            = icon('fa', 'plus-circle')
          フェーズを追加
    - elsif @project_phase.blank? && @project_phases.present?
    - else
      .goal-show-info__contents
        %p.empty empty
        = link_to new_project_project_phase_path(@project) do
          %span.blue
            = icon('fa', 'plus')
          フェーズを追加    
    - if @project_phases.present?
      - @project_phases.each do |phase|
        .goal-show-info__contents
          .goal-show-info__contents__phase-header
            .goal-show-info__contents__phase-header__title
              .goal-show-info__contents__phase-header__title__nav
                %p 
                  = link_to api_phase_path(phase), method: :patch do
                    = icon('fa', 'check-circle')
                    フェーズを切り替える
                .goal-show-info__contents__phase-header__title__nav__link
                  = link_to edit_project_project_phase_path(@project, phase) do
                    = icon('fa', 'edit')
                  = link_to project_project_phase_path(@project, phase), method: :delete do
                    = icon('fa', 'trash')
              %p.goal-show-info__contents__phase-header__title__phase
                = phase.title
          .goal-show-info__contents__top
            .goal-show-info__contents__top__phase
              %p#phase_data{data: {phase: {id: phase.id}}}
            .goal-show-info__contents__top__tasks
              .goal-show-info__contents__top__tasks__title
                %p タスクのチェック
              - if phase.project_tasks.present?
                - sort_created_at(phase.project_tasks).each do |task|
                  .goal-show-info__contents__top__tasks__index
                    .goal-show-info__contents__top__tasks__index__timestamp
                      %p.goal-show-info__contents__accbox__accshow__checkbox__timestamp
                        - if task.task_flg == true
                          = "#{task.updated_at.year}年#{task.updated_at.mon}月#{task.updated_at.day}日"
                    .goal-show-info__contents__top__tasks__index__checkbox
                      .goal-show-info__contents__top__tasks__index__checkbox__main
                        %label.goal-show-info__contents__accbox__accshow__checkbox__label
                          - if task.user_id == current_user.id
                            - if task.task_flg == true
                              %input.project-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox", :checked => "checked"}
                            - else
                              %input.project-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox"}
                            = task.title
                            #task{data: {task: {id: task.id}}}
                          - else
                            - if task.task_flg == true
                              %span
                                = icon('fa', 'check-square')
                            - else                            
                            = task.title
                          #task{data: {task: {id: task.id}}}
                      .goal-show-info__contents__top__tasks__index__checkbox__link
                        = link_to edit_project_phase_project_task_path(phase, task) do
                          = icon('fa', 'edit')
                        = link_to new_project_phase_project_task_path(phase), method: :delete do
                          = icon('fa', 'trash')
              - else
                %p タスクはありません          
              .goal-show-info__contents__top__tasks__create
                = link_to new_project_phase_project_task_path(phase) do
                  = icon('fa', 'tasks')
                  タスクの作成
          .goal-show-info__contents__bottom
            .goal-show-info__contents__bottom__accbox
              %label.goal-show-info__contents__bottom__accbox__label
                %span
                  = icon('fa', 'comment')
                コメントメニュー
                = icon('fa', 'angle-down')
                %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
                .goal-show-info__contents__bottom__accbox__accshow
                  .goal-show-info__contents__bottom__comments
                    .goal-show-info__contents__bottom__comments__content
                      - if phase.project_comments.present?
                        - sort_created_at(phase.project_comments).each do |comment|
                          .goal-show-info__contents__bottom__comments__content__comment
                            %p 
                              = icon('fa', 'user-edit')
                              = comment.user.name
                              %br
                              = comment.content
                            = link_to project_phase_project_comment_path(phase,comment), method: :delete do
                              = icon('fa', 'trash')
                    .goal-show-info__contents__bottom__comments__form{data: {commentphase: {id: phase.id}}}
                      .token{data: {authenticity: {token: form_authenticity_token}}}
                      %input{:type => "text", :placeholder => "コメント"}
                      %button.project_comment_button
                        = icon('fa', 'paper-plane')
        .goal-show-info__create
          = link_to new_project_project_phase_path(@project) do
            %span.blue
              = icon('fa', 'plus-circle')
            フェーズを追加
    - else