config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'goals#index'
  resources :static_pages do
    collection do
      get 'about'
      get 'help'
    end
  end

  resources :users do
    resources :goals, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :goals, only: [:new, :index] do
    resources :phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :minds
  end

  resources :phases, only: [:show] do
    resources :tasks
    resources :comments
  end

  resources :tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :phases, only: [:index, :edit, :update], defaults: { format: 'json' }
  end

  resources :teams do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    member do
      get 'activate_user'
      get 'deactivate_user'
    end
  end

  resources :projects, only: [:index] do
    resources :project_phases, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :project_minds
  end

  resources :project_phases, only: [:show] do
    resources :project_tasks
    resources :project_comments
  end

  resources :project_tasks do
    collection do
      get 'change_task_flg'
    end
  end

  namespace :api do
    resources :project_phases, only: :index, defaults: { format: 'json' }
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :phases, dependent: :destroy
  has_many :minds, dependent: :destroy

  def search_phase(goal)
    phases.find_by(title: goal.phase_title)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :move_to_sign_in
  before_action :set_goal, except: [:new, :create, :index]

  def new
    @goal = Goal.new
  end

  def create
    goal = Goal.new(goal_params)
    if goal.save
      redirect_to goals_path
    else
      render :new
    end
  end

  def index
    @goals = current_user.goals.includes(:phases).order("created_at DESC")
  end

  def show
    @phase = Phase.find_by(title: @goal.phase_title)
    @phases = @goal.phases.where.not(title: @goal.phase_title).order("created_at ASC")
    @minds = sort_created_at(@goal.minds)
    if @phase.present?
      @tasks = sort_created_at(@phase.tasks)
      @comment = Comment.new
      @comments = sort_created_at(@phase.comments)
    end
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to goals_path
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_path
  end

  private

    def goal_params
      params.require(:goal).permit(:title, :phase_title).merge(user_id: current_user.id)
    end

    def set_goal
      @goal = current_user.goals.find(params[:id])
    end
end

app/views/goals/_phase.html.haml
.goal-show-info__contents
  - if phase.title == @goal.phase_title
    .goal-show-info__contents__status
      %p 現在進行中のフェーズ
  - else
    .goal-show-info__contents__status
      %p 進行中に設定
  .goal-show-info__contents__phase-header
    .goal-show-info__contents__phase-header__phase-title
      %p
        = phase.title
    .goal-show-info__contents__phase-header__link
      = link_to edit_goal_phase_path(@goal,phase) do
        = icon('fa', 'edit')
      = link_to goal_phase_path(@goal,phase), method: :delete do
        = icon('fa', 'trash')
  .goal-show-info__contents__top
    .goal-show-info__contents__top__phase
      %p#phase_data{data: {phase: {id: phase.id}}}
    .goal-show-info__contents__top__tasks
      .goal-show-info__contents__top__tasks__title
        %p フェーズ内のタスク
      -# = link_to 'タスクを作成', new_phase_task_path(phase)
      - unless phase.tasks.empty?
        - sort_created_at(phase.tasks).each do |task|
          .goal-show-info__contents__top__tasks__index
            .goal-show-info__contents__top__tasks__index__timestamp
              %p.goal-show-info__contents__accbox__accshow__checkbox__timestamp
                - unless task.task_flg == false
                  = "#{task.updated_at.year}年#{task.updated_at.mon}月#{task.updated_at.day}日"
            .goal-show-info__contents__top__tasks__index__checkbox
              .goal-show-info__contents__top__tasks__index__checkbox__main
                %label.goal-show-info__contents__accbox__accshow__checkbox__label
                  - if task.task_flg == true
                    %input.goal-show-info__contents__accbox__accshow__checkbox__inputt{:type => "checkbox", :checked => "checked"}
                  - else
                    %input.goal-show-info__contents__accbox__accshow__checkbox__inputt{:type => "checkbox"}
                  = task.title
                  #task{data: {task: {id: task.id}}}
              .goal-show-info__contents__top__tasks__index__checkbox__link
                = link_to edit_phase_task_path(phase, task) do
                  = icon('fa', 'edit')
                = link_to new_phase_task_path(phase), method: :delete do
                  = icon('fa', 'trash')
      - else
        %p タスクはありません          
      .goal-show-info__contents__top__tasks__create
        = link_to new_goal_phase_path(@goal) do
          = icon('fa', 'tasks')
          作成
  .goal-show-info__contents__bottom
    .goal-show-info__contents__bottom__accbox
      %label.goal-show-info__contents__bottom__accbox__label
        コメントメニュー
        = icon('fa', 'angle-down')
        %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
        .goal-show-info__contents__bottom__accbox__accshow
          .goal-show-info__contents__bottom__comments
            - unless phase.comments.empty?
              - sort_created_at(phase.comments).each do |comment|
                .goal-show-info__contents__bottom__comments__content
                  %p 
                    = comment.content
                  = link_to phase_comment_path(phase,comment), method: :delete do
                    = icon('fa', 'trash')
            .goal-show-info__contents__bottom__comments__form{data: {commentphase: {id: phase.id}}}
              .token{data: {authenticity: {token: form_authenticity_token}}}
              %input{:type => "text", :placeholder => "コメント"}
              %button.comment_button
                = icon('fa', 'paper-plane')
.goal-show-info__create
  = link_to new_goal_phase_path(@goal) do
    = icon('fa', 'plus-circle')
    フェーズを追加

app/views/goals/edit.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'edit')
        タイトルの編集
    = form_with model: [current_user, @goal], url: user_goal_path, class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"

app/views/goals/index.html.haml
- provide(:title, "ダッシュボード")
.goal-wrapper
  = render 'shared/header'
  .goal-index__container
    - if @goals.present?
      .goal-index__container__header
        .goal-index__container__header__title
          %p
            = "目標の総数：#{@goals.count}"
      - @goals.each do |goal|
      - phase = goal.search_phase(goal)
      - tasks = phase.tasks
      - checked_tasks = phase.search_checked_tasks(phase)
      - unchecked_tasks = phase.search_unchecked_tasks(phase)
        .goal-index__container__contents
          .goal-index__container__contents__title
            %h2
              = goal.title
          .goal-index__container__contents__main
            .goal-index__container__contents__main__phase
              .goal-index__container__contents__main__phase__title
                - if goal.phases.present?
                  - if goal.phase_title.present?
                    %p
                      = phase.title
                  - else
                    %p
                      フェーズが設定されていません
                - else
                  %p
                    フェーズを作成してください
              .goal-index__container__contents__main__phase__tasks
                .goal-index__container__contents__main__phase__tasks__unfinished-task
                  - if tasks.present?
                    %p
                      = "残りのタスク：#{unchecked_tasks.count}"
                    %ul
                      - unchecked_tasks.each do |task|
                        %li
                          = icon('fa', 'caret-right', class: 'caret')
                          = task.title
                  - else
                    %p タスク無し
                .goal-index__container__contents__main__phase__tasks__finished-task
                  .goal-index__container__contents__main__finished-task__index
                    - if tasks.present?
                      %p
                        = "完了したタスク：#{sort_tasks(phase.tasks).count}"
                        %ul
                          - checked_tasks.each do |task|
                            %li
                              = icon('fa', 'check-square', class: 'check-square')
                              = task.title
                    - else
                      %p タスク無し
            .goal-index__container__contents__main__side-bar
              .goal-index__container__contents__main__side-bar__links
                .goal-index__container__contents__main__side-bar__links__show
                  = link_to '詳細ページに移動', user_goal_path(current_user, goal)
                .goal-index__container__contents__main__side-bar__links__edit
                  %button.goal-title-edit
                    = link_to '目標名の編集', edit_user_goal_path(current_user, goal)
                  %button.goal-title-delete
                    = link_to '目標を削除', user_goal_path(current_user, goal), method: :delete
    - else
      .goal-index__container__header
        .goal-index__container__header__title
          %p
            目標の総数：0
      .goal-index__container__contents
        .goal-index__container__contents__top
          .goal-index__container__contents__top__title
            %p
              目標を作成しましょう

app/views/goals/new.html.haml
.form-wrapper
  .form-wrapper__container
    .form-wrapper__container__header
      %p
        = icon('fa', 'plus-circle')
        目標の新規作成
    = form_with model: [current_user, @goal], url: user_goals_path(current_user), class: "form-wrapper__container__form", local: true do |f|
      .form-wrapper__container__form__field
        %span
          = icon('fa', 'pen')
        = f.text_field :title, class: "form-wrapper__container__form__field__input", placeholder: 'タイトル', autofocus: true
      .form-wrapper__container__form__field
        = f.submit "Create", class: "form-wrapper__container__form__field__button"

app/views/goals/show.html.haml
.goal-wrapper
  = render 'shared/header'
  .goal-show-info
    .goal-show-info__header
      %h2.goal-show-info__header__title
        = @goal.title
      .goal-show-info__header__remind
        - if @minds.present?
          .goal-show-info__header__remind__title
            %p 
              = icon('fa', 'clipboard-list')
              リマインド
          - @minds.each do |mind|
            .goal-show-info__header__remind__index
              %p 
                = "・#{mind.title}"
              .goal-show-info__header__remind__index__link
                = link_to edit_goal_mind_path(@goal, mind) do
                  = icon('fa', 'edit')
                = link_to goal_mind_path(@goal, mind), method: :delete do
                  = icon('fa', 'trash')
        - else
          %p リマインドはありません
      .goal-show-info__header__link
        = link_to new_goal_mind_path(@goal) do
          %span.blue
            = icon('fa', 'plus-circle')
          リマインドを追加する
    - if @phase.present?
      .goal-show-info__contents
        .goal-show-info__contents__phase-header
          .goal-show-info__contents__phase-header__title
            .goal-show-info__contents__phase-header__title__nav
              %p 
                %span.blue 
                  = icon('fa', 'check-circle')
                進行中のフェーズ
              .goal-show-info__contents__phase-header__title__nav__link
                = link_to edit_goal_phase_path(@goal,@phase) do
                  = icon('fa', 'edit')
                = link_to goal_phase_path(@goal,@phase), method: :delete do
                  = icon('fa', 'trash')
            %p.goal-show-info__contents__phase-header__title__phase
              = @phase.title
        .goal-show-info__contents__top
          .goal-show-info__contents__top__phase
            %p#phase_data{data: {phase: {id: @phase.id}}}
          .goal-show-info__contents__top__tasks
            .goal-show-info__contents__top__tasks__title
              %p タスクのチェック
            - if @tasks.present?
              - @tasks.each do |task|
                .goal-show-info__contents__top__tasks__index
                  .goal-show-info__contents__top__tasks__index__timestamp
                    %p.goal-show-info__contents__accbox__accshow__checkbox__timestamp
                      - if task.task_flg == true
                        = "#{task.updated_at.year}年#{task.updated_at.mon}月#{task.updated_at.day}日"
                  .goal-show-info__contents__top__tasks__index__checkbox
                    .goal-show-info__contents__top__tasks__index__checkbox__main
                      %label.goal-show-info__contents__accbox__accshow__checkbox__label
                        - if task.task_flg == true
                          %input.goal-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox", :checked => "checked"}
                        - else
                          %input.goal-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox"}
                        = task.title
                        #task{data: {task: {id: task.id}}}
                    .goal-show-info__contents__top__tasks__index__checkbox__link
                      = link_to edit_phase_task_path(@phase, task) do
                        = icon('fa', 'edit')
                      = link_to phase_task_path(@phase, task), method: :delete do
                        = icon('fa', 'trash')
            - else
              %p タスクはありません          
            .goal-show-info__contents__top__tasks__create
              = link_to new_phase_task_path(@phase) do
                = icon('fa', 'tasks')
                タスクの作成
        .goal-show-info__contents__bottom
          .goal-show-info__contents__bottom__accbox
            %label.goal-show-info__contents__bottom__accbox__label
              %span
                = icon('fa', 'comment')
              コメントメニュー
              = icon('fa', 'angle-down')
              %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
              .goal-show-info__contents__bottom__accbox__accshow
                .goal-show-info__contents__bottom__comments
                  .goal-show-info__contents__bottom__comments__content
                    - if @comments.present?
                      - @comments.each do |comment|
                        .goal-show-info__contents__bottom__comments__content__comment
                          %p 
                            = comment.content
                          = link_to phase_comment_path(@phase, comment), method: :delete do
                            = icon('fa', 'trash')
                    - else
                      .goal-show-info__contents__bottom__comments__content__comment
                  .goal-show-info__contents__bottom__comments__form{data: {commentphase: {id: @phase.id}}}
                    .token{data: {authenticity: {token: form_authenticity_token}}}
                    %input{:type => "text", :placeholder => "コメント"}
                    %button.comment_button
                      = icon('fa', 'paper-plane')
      .goal-show-info__create
        = link_to new_goal_phase_path(@goal) do
          %span.blue
            = icon('fa', 'plus-circle')
          フェーズを追加
    - elsif @phase.blank? && @phases.present?
    - else
      .goal-show-info__contents
        = link_to new_goal_phase_path(@goal) do
          %span.blue
            = icon('fa', 'plus-circle')
          フェーズを追加    
    - if @phases.present?
      - @phases.each do |phase|
        .goal-show-info__contents
          .goal-show-info__contents__phase-header
            .goal-show-info__contents__phase-header__title
              .goal-show-info__contents__phase-header__title__nav
                %p 
                  = link_to edit_api_phase_path(phase) do
                    = icon('fa', 'check-circle')
                    フェーズを切り替える
                .goal-show-info__contents__phase-header__title__nav__link
                  = link_to edit_goal_phase_path(@goal, phase) do
                    = icon('fa', 'edit')
                  = link_to goal_phase_path(@goal, phase), method: :delete do
                    = icon('fa', 'trash')
              %p.goal-show-info__contents__phase-header__title__phase
                = phase.title
          .goal-show-info__contents__top
            .goal-show-info__contents__top__phase
              %p#phase_data{data: {phase: {id: phase.id}}}
            .goal-show-info__contents__top__tasks
              .goal-show-info__contents__top__tasks__title
                %p タスクのチェック
              - if phase.tasks.present?
                - sort_created_at(phase.tasks).each do |task|
                  .goal-show-info__contents__top__tasks__index
                    .goal-show-info__contents__top__tasks__index__timestamp
                      %p.goal-show-info__contents__accbox__accshow__checkbox__timestamp
                        - if task.task_flg == true
                          = "#{task.updated_at.year}年#{task.updated_at.mon}月#{task.updated_at.day}日"
                    .goal-show-info__contents__top__tasks__index__checkbox
                      .goal-show-info__contents__top__tasks__index__checkbox__main
                        %label.goal-show-info__contents__accbox__accshow__checkbox__label
                          - if task.task_flg == true
                            %input.goal-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox", :checked => "checked"}
                          - else
                            %input.goal-show-info__contents__accbox__accshow__checkbox__input{:type => "checkbox"}
                          = task.title
                          #task{data: {task: {id: task.id}}}
                      .goal-show-info__contents__top__tasks__index__checkbox__link
                        = link_to edit_phase_task_path(phase, task) do
                          = icon('fa', 'edit')
                        = link_to phase_task_path(phase, task), method: :delete do
                          = icon('fa', 'trash')
              - else
                %p タスクはありません          
              .goal-show-info__contents__top__tasks__create
                = link_to new_phase_task_path(phase) do
                  = icon('fa', 'tasks')
                  タスクの作成
          .goal-show-info__contents__bottom
            .goal-show-info__contents__bottom__accbox
              %label.goal-show-info__contents__bottom__accbox__label
                %span
                  = icon('fa', 'comment')
                コメントメニュー
                = icon('fa', 'angle-down')
                %input.goal-show-info__contents__bottom__accbox__cssacc{:type => "checkbox"}
                .goal-show-info__contents__bottom__accbox__accshow
                  .goal-show-info__contents__bottom__comments
                    .goal-show-info__contents__bottom__comments__content
                      - if phase.comments.present?
                        - sort_created_at(phase.comments).each do |comment|
                          .goal-show-info__contents__bottom__comments__content__comment
                            %p 
                              = comment.content
                            = link_to phase_comment_path(phase,comment), method: :delete do
                              = icon('fa', 'trash')
                    .goal-show-info__contents__bottom__comments__form{data: {commentphase: {id: phase.id}}}
                      .token{data: {authenticity: {token: form_authenticity_token}}}
                      %input{:type => "text", :placeholder => "コメント"}
                      %button.comment_button
                        = icon('fa', 'paper-plane')
        .goal-show-info__create
          = link_to new_goal_phase_path(@goal) do
            %span.blue
              = icon('fa', 'plus-circle')
            フェーズを追加